### ISSUE TITLE
Advanced cron expression

### ISSUE THREAD

**Issue by tarkal** [ff36/halo-gui#331]
The advanced cron expression does not save custom entries. For example if I want to setup a schedule every 2 mins I would want to enter `0 0/2 * 1/1 * ? *`. However if I do this and try to save it the new value is not passed back to the server.

Also it should be possible to set the number of minutes in the cron maker.

![screen shot 2016-06-28 at 12 28 55](https://cloud.githubusercontent.com/assets/7042623/16417322/936863b8-3d45-11e6-97b5-e7c523e74825.png)

**Comment by tarkal** [comment]
Actually the custom expression is being received by the server and being implemented but its just not displaying correctly on the page.

**Comment by sweety-wo** [comment]
Actually,
We have used [angular-quartz-cron](https://github.com/RajanRastogi/angular-quartz-cron)  library which is based on [angular-cron-jobs](https://github.com/jacobscarter/angular-cron-jobs).

Currently,  [angular-cron-jobs](https://github.com/jacobscarter/angular-cron-jobs) **not support** generalized selections such as a one button click for "**Every Five Minutes**" 

![angular-cron-jobs](https://cloud.githubusercontent.com/assets/14175105/16447687/519fe6f6-3e0b-11e6-8696-45babcdd018e.png)

**Comment by tarkal** [comment]
Can you contact the author and find out what their timeline is? This is very important because 99% of schedules will be between 10 seconds and 5 mins.

In the mean time we need to make it so that if the user selects the advanced option it will disable the cron expression generator. Instead of it being an supplementary toggle it needs to be a replacement text box. The API will still sanitise cron expressions and if an invalid expression is entered the API will default back to every minute.

Either that or find another library...

**Comment by sweety-wo** [comment]
For author contact  I have open issue on https://github.com/RajanRastogi/angular-quartz-cron/issues/2

For now, I have disable cron expression generator if advanced option and con expression string has **`/`**.

See images **Read Mode:**
**if con expression string has `/` then display con expression string**

![corn_has_slash](https://cloud.githubusercontent.com/assets/14175105/16454038/a421c7f2-3e2c-11e6-8820-5958327caf1d.png)

**otherwise**

![corn_has_not_slash](https://cloud.githubusercontent.com/assets/14175105/16454087/de10e2ae-3e2c-11e6-85d7-7ed8b38b13aa.png)


**Edit Mode:** 

Disable cron expression generator if advanced option and con expression string has **`/`**.

![edit_advance](https://cloud.githubusercontent.com/assets/14175105/16454170/3c6faa4c-3e2d-11e6-94be-a142d936a5ce.png)

![edit_not_advance](https://cloud.githubusercontent.com/assets/14175105/16454212/72db2c3c-3e2d-11e6-9282-f0a6fd417bf8.png)

**Comment by sweety-wo** [comment]
I think for now remove cron expression generator and display [cron expression generator](http://www.cronmaker.com/)  link  for generate online cron expression and use it  until author response or find new library for cron expression generator.

What you think?

**Comment by tarkal** [comment]
What is wrong with your solution above of disabling the maker if it contains `/`?

**Comment by sweety-wo** [comment]
Actually,
Just suggest you because in read mode **Schedule** display different for cron expression has `/` or cron expression has not `/` .

**Comment by sweety-wo** [comment]
- Added support for 'interval'  and 'second' option for all schedule.
![cron interval and second](https://cloud.githubusercontent.com/assets/14175105/18051963/621fcf0c-6e15-11e6-819b-1134f2485c46.gif)
