### ISSUE TITLE
On/Off Buttons not functioning

### ISSUE THREAD

**Issue by tblake84** [ff36/halo-gui#440]
On/Off value buttons do not function on Node pages.  Can not turn on or off MDBU ports, alarms, or any alert or safe state buttons.

**Comment by tarkal** [comment]
We had to redesign the SOLiD plugins. This feature is not yet implemented. We plan to re-implement this is release 1.3.2. Apologies 

Tarka L'Herpiniere

On Wed, Aug 24, 2016 at 19:17 tblake84

<
mailto:tblake84 <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

On/Off value buttons do not function on Node pages. Can not turn on or off MDBU ports, alarms, or any alert or safe state buttons.

—

You are receiving this because you are subscribed to this thread.

Reply to this email directly,
https://github.com/ff36/halo-gui/issues/440
, or
